In [1]:
#r'C:\Users\Vaclav\Documents\Diploma\Dirty Signals\Test\Test14\snd-P3.20160212.0028.3.wav'
import os
import cv2
import thinkplot
from thinkdsp import read_wave
import numpy as np
from matplotlib import pyplot as plt

%matplotlib inline
#The line above is necesary to show Matplotlib's plots inside a Jupyter Notebook

# root="TEST", formats=['png']
def plot_save(wave, root, formats,**options):
        fs = wave.frequencies()
        i = None
        fs = fs[:i]
        ts = wave.times()

        # make the array
        size = len(fs), len(ts)
        array = np.zeros(size, dtype=np.float)

        # copy amplitude from each spectrum into a column of the array
        for j, t in enumerate(ts):
            spectrum = wave.spec_map[t]
            array[:, j] = spectrum.amps[:i]
        
        thinkplot.pcolor(ts, fs, array, pcolor=True, contour=False, **options)
        thinkplot.save(root, formats, **options)

In [2]:
#wave = read_wave(r"C:\Users\Vaclav\Documents\Diploma\Clean Signals\ETHALON_SIGNAL\snd-P3.20150222.1755.0.wav")
#wave.normalize()
#sig = wave.make_spectrogram(1024)
#plot_save(sig, "snd-P3.20160212.0028.3", ['png'])

In [3]:
#-----Reading the image-----------------------------------------------------
#img = cv2.imread('snd-P3.20160212.0028.3.png', 1)

#-----Converting image to LAB Color model----------------------------------- 
#lab = cv2.cvtColor(img, cv2.COLOR_BGR2LAB)
#cv2.imshow("lab",lab)

#-----Splitting the LAB image to different channels-------------------------
#l, a, b = cv2.split(lab)
#cv2.imshow('l_channel', l)
#cv2.imshow('a_channel', a)
#cv2.imshow('b_channel', b)

#-----Applying CLAHE to L-channel-------------------------------------------
#clahe = cv2.createCLAHE(clipLimit=3.0, tileGridSize=(8,8))
#cl = clahe.apply(l)
#cv2.imshow('CLAHE output', cl)

#-----Merge the CLAHE enhanced L-channel with the a and b channel-----------
#limg = cv2.merge((cl,a,b))
#cv2.imshow('limg', limg)

#-----Converting image from LAB Color model to RGB model--------------------
#final = cv2.cvtColor(limg, cv2.COLOR_LAB2BGR)
#cv2.imshow('final', final)

#-----Cropping image and saving it-------------------------------------------------------
#crop_img = img[150:150+895,235:235+1330]
#cv2.imwrite('snd-P3.20160212.0028.3.png',crop_img)

In [4]:
#Show the image with matplotlib
#plt.imshow(crop_img)
#plt.axis('off')
#plt.show()

In [5]:
#gray = cv2.cvtColor(crop_img,cv2.COLOR_BGR2GRAY)
#edges = cv2.Canny(gray, 75, 150)
#lines = cv2.HoughLinesP(edges, 1, np.pi/180, 30, maxLineGap=250)
#for line in lines:
#    x1, y1, x2, y2 = line[0]
#    cv2.line(crop_img, (x1, y1), (x2, y2), (0, 0, 128), 1)

In [6]:
#edges = cv2.Canny(gray,50,150,apertureSize = 7)
#minLineLength = 100
#maxLineGap = 10
#lines = cv2.HoughLinesP(edges,1,np.pi/180,100,minLineLength,maxLineGap)
#for x1,y1,x2,y2 in lines[0]:
#    cv2.line(img,(x1,y1),(x2,y2),(0,255,0),2)

#cv2.imwrite(os.path.join(linePath, 'lines_'+filename),crop_img)
#cv2.imwrite(os.path.join(edgePath, 'edges_'+filename),edges)

In [7]:
#len(lines)

In [8]:
#Show the image with matplotlib
#limg = cv2.imread('snd-P3.20160212.0028.3_lines.png', 1)
#plt.imshow(limg)
#plt.axis('off')
#plt.show()

In [9]:
edgePath = r'C:\Users\Vaclav\Documents\Diploma\Notebooks\Classifier\ImageBase\Edges'
linePath = r'C:\Users\Vaclav\Documents\Diploma\Notebooks\Classifier\ImageBase\Lines'

In [10]:
for filename in os.listdir('C:/Users/Vaclav/Documents/Diploma/Clean Signals/ETHALON_SIGNAL'):
    wave = read_wave('C:/Users/Vaclav/Documents/Diploma/Clean Signals/ETHALON_SIGNAL/'+filename)
    wave.normalize()
    filename = os.path.splitext(filename)[0]
    sig = wave.make_spectrogram(1024)
    plot_save(sig, filename, ['png'])
    filename = filename+'.png'
    #-----Reading the image-----------------------------------------------------
    img = cv2.imread(filename, 1)

    #-----Converting image to LAB Color model----------------------------------- 
    lab = cv2.cvtColor(img, cv2.COLOR_BGR2LAB)
    #cv2.imshow("lab",lab)

    #-----Splitting the LAB image to different channels-------------------------
    l, a, b = cv2.split(lab)
    #cv2.imshow('l_channel', l)
    #cv2.imshow('a_channel', a)
    #cv2.imshow('b_channel', b)

    #-----Applying CLAHE to L-channel-------------------------------------------
    clahe = cv2.createCLAHE(clipLimit=3.0, tileGridSize=(8,8))
    cl = clahe.apply(l)
    #cv2.imshow('CLAHE output', cl)

    #-----Merge the CLAHE enhanced L-channel with the a and b channel-----------
    limg = cv2.merge((cl,a,b))
    #cv2.imshow('limg', limg)

    #-----Converting image from LAB Color model to RGB model--------------------
    final = cv2.cvtColor(limg, cv2.COLOR_LAB2BGR)
    #cv2.imshow('final', final)

    #-----Cropping image and saving it-------------------------------------------------------
    #crop_img = img[150:150+895,235:235+1330]
    crop_img = img
    #cv2.imwrite(filename,crop_img)
    
    gray = cv2.cvtColor(crop_img,cv2.COLOR_BGR2GRAY)
    edges = cv2.Canny(gray, 75, 150)
    lines = cv2.HoughLinesP(edges, 1, np.pi/180, 30, maxLineGap=250)
    #lines = cv2.HoughLinesP(E,rho = 1,theta = 1*np.pi/180,threshold = 100,minLineLength = 100,maxLineGap = 50)
    for line in lines:
        x1, y1, x2, y2 = line[0]
        cv2.line(crop_img, (x1, y1), (x2, y2), (0, 0, 128), 1)
    cv2.imwrite(os.path.join(linePath, 'lines_'+filename),crop_img)
    cv2.imwrite(os.path.join(edgePath, 'edges_'+filename),edges)    

No handles with labels found to put in legend.


Writing snd-P3.20150221.0145.0.png


No handles with labels found to put in legend.


Writing snd-P3.20150221.0156.0.png


No handles with labels found to put in legend.


Writing snd-P3.20150221.0201.0.png


No handles with labels found to put in legend.


Writing snd-P3.20150221.0201.1.png


No handles with labels found to put in legend.


Writing snd-P3.20150221.0201.2.png


No handles with labels found to put in legend.


Writing snd-P3.20150222.0644.0.png


No handles with labels found to put in legend.


Writing snd-P3.20150222.0831.0.png


No handles with labels found to put in legend.


Writing snd-P3.20150222.0843.0.png


No handles with labels found to put in legend.


Writing snd-P3.20150222.0843.1.png


No handles with labels found to put in legend.


Writing snd-P3.20150222.0843.2.png


No handles with labels found to put in legend.


Writing snd-P3.20150222.0843.3.png


No handles with labels found to put in legend.


Writing snd-P3.20150222.0907.0.png


No handles with labels found to put in legend.


Writing snd-P3.20150222.0907.1.png


No handles with labels found to put in legend.


Writing snd-P3.20150222.0908.0.png


No handles with labels found to put in legend.


Writing snd-P3.20150222.0908.1.png


No handles with labels found to put in legend.


Writing snd-P3.20150222.0911.0.png


No handles with labels found to put in legend.


Writing snd-P3.20150222.0911.4.png


No handles with labels found to put in legend.


Writing snd-P3.20150222.0912.2.png


No handles with labels found to put in legend.


Writing snd-P3.20150222.0913.2.png


No handles with labels found to put in legend.


Writing snd-P3.20150222.0913.3.png


No handles with labels found to put in legend.


Writing snd-P3.20150222.0914.0.png


No handles with labels found to put in legend.


Writing snd-P3.20150222.0914.5.png


No handles with labels found to put in legend.


Writing snd-P3.20150222.1029.0.png


No handles with labels found to put in legend.


Writing snd-P3.20150222.1750.0.png


No handles with labels found to put in legend.


Writing snd-P3.20150222.1755.0.png


No handles with labels found to put in legend.


Writing snd-P3.20150222.1757.0.png


No handles with labels found to put in legend.


Writing snd-P3.20150222.1759.8.png


No handles with labels found to put in legend.


Writing snd-P3.20150222.1841.0.png


No handles with labels found to put in legend.


Writing snd-P3.20150222.1843.0.png


No handles with labels found to put in legend.


Writing snd-P3.20151026.0755.25.png


No handles with labels found to put in legend.


Writing snd-P3.20151026.0755.26.png


No handles with labels found to put in legend.


Writing snd-P3.20151026.0755.27.png


No handles with labels found to put in legend.


Writing snd-P3.20151026.0755.29.png


No handles with labels found to put in legend.


Writing snd-P3.20151026.0755.30.png


No handles with labels found to put in legend.


Writing snd-P3.20151026.0755.31.png


No handles with labels found to put in legend.


Writing snd-P3.20151026.0755.32.png


No handles with labels found to put in legend.


Writing snd-P3.20151026.0755.33.png


No handles with labels found to put in legend.


Writing snd-P3.20151026.0755.38.png


No handles with labels found to put in legend.


Writing snd-P3.20151026.0755.39.png


No handles with labels found to put in legend.


Writing snd-P3.20151026.0756.0.png


No handles with labels found to put in legend.


Writing snd-P3.20151026.0756.1.png


No handles with labels found to put in legend.


Writing snd-P3.20151026.0757.10.png


No handles with labels found to put in legend.


Writing snd-P3.20151026.0757.2.png


No handles with labels found to put in legend.


Writing snd-P3.20151026.0757.3.png


No handles with labels found to put in legend.


Writing snd-P3.20151026.0757.4.png


No handles with labels found to put in legend.


Writing snd-P3.20151026.0758.3.png


No handles with labels found to put in legend.


Writing snd-P3.20151026.0758.7.png


No handles with labels found to put in legend.


Writing snd-P3.20151026.0758.8.png


No handles with labels found to put in legend.


Writing snd-P3.20151026.0819.7.png


No handles with labels found to put in legend.


Writing snd-P3.20151026.0819.8.png


No handles with labels found to put in legend.


Writing snd-P3.20151026.0849.1.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.1934.0.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.1934.1.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.1934.2.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.1934.3.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.1934.4.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.1934.5.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.1934.6.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.1935.0.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.1935.1.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.1935.2.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.1935.3.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.1935.4.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.1935.5.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.1935.6.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.2052.0.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.2052.1.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.2052.10.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.2052.11.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.2052.12.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.2052.13.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.2052.2.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.2052.3.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.2052.4.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.2052.5.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.2052.6.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.2052.7.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.2052.8.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.2052.9.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.2124.6.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.2124.7.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.2250.0.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.2250.1.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.2250.10.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.2250.11.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.2250.12.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.2250.13.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.2250.14.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.2250.15.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.2250.16.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.2250.2.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.2250.3.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.2250.4.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.2250.5.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.2250.6.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.2250.7.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.2250.8.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.2250.9.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.2342.0.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.2342.1.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.2342.2.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.2342.3.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.2342.4.png


No handles with labels found to put in legend.


Writing snd-P3.20151031.2342.5.png


No handles with labels found to put in legend.


Writing snd-P3.20151101.0024.2.png


No handles with labels found to put in legend.


Writing snd-P3.20151101.0024.3.png


No handles with labels found to put in legend.


Writing snd-P3.20151101.0025.0.png


No handles with labels found to put in legend.


Writing snd-P3.20151101.0025.1.png


No handles with labels found to put in legend.


Writing snd-P3.20151101.0025.2.png


No handles with labels found to put in legend.


Writing snd-P3.20151101.0025.3.png


No handles with labels found to put in legend.


Writing snd-P3.20151101.0034.1.png


No handles with labels found to put in legend.


Writing snd-P3.20151101.2149.0.png


No handles with labels found to put in legend.


Writing snd-P3.20151101.2149.1.png


No handles with labels found to put in legend.


Writing snd-P3.20151101.2149.2.png


No handles with labels found to put in legend.


Writing snd-P3.20151102.0508.26.png


No handles with labels found to put in legend.


Writing snd-P3.20151102.0508.27.png


No handles with labels found to put in legend.


Writing snd-P3.20151102.0508.29.png


No handles with labels found to put in legend.


Writing snd-P3.20151102.0508.30.png


No handles with labels found to put in legend.


Writing snd-P3.20151102.0509.3.png


No handles with labels found to put in legend.


Writing snd-P3.20151102.0509.4.png


No handles with labels found to put in legend.


Writing snd-P3.20151102.0533.0.png


No handles with labels found to put in legend.


Writing snd-P3.20151102.0538.0.png


No handles with labels found to put in legend.


Writing snd-P3.20151102.0538.1.png


No handles with labels found to put in legend.


Writing snd-P3.20151102.0538.2.png


No handles with labels found to put in legend.


Writing snd-P3.20151102.0538.3.png


No handles with labels found to put in legend.


Writing snd-P3.20151102.0539.0.png


No handles with labels found to put in legend.


Writing snd-P3.20151102.1841.4.png


No handles with labels found to put in legend.


Writing snd-P3.20151103.0032.0.png


No handles with labels found to put in legend.


Writing snd-P3.20151103.0032.1.png


No handles with labels found to put in legend.


Writing snd-P3.20151103.0032.2.png


No handles with labels found to put in legend.


Writing snd-P3.20151103.0032.3.png


No handles with labels found to put in legend.


Writing snd-P3.20151103.0032.4.png


No handles with labels found to put in legend.


Writing snd-P3.20151103.0032.5.png


No handles with labels found to put in legend.


Writing snd-P3.20151103.0032.7.png


No handles with labels found to put in legend.


Writing snd-P3.20151103.0033.5.png


No handles with labels found to put in legend.


Writing snd-P3.20151103.0033.7.png


No handles with labels found to put in legend.


Writing snd-P3.20160210.0956.0.png


No handles with labels found to put in legend.


Writing snd-P3.20160210.0956.1.png


No handles with labels found to put in legend.


Writing snd-P3.20160210.0956.5.png


No handles with labels found to put in legend.


Writing snd-P3.20160211.0848.5.png


No handles with labels found to put in legend.


Writing snd-P3.20160211.0849.5.png


No handles with labels found to put in legend.


Writing snd-P3.20160211.0904.1.png


No handles with labels found to put in legend.


Writing snd-P3.20160211.0906.1.png


No handles with labels found to put in legend.


Writing snd-P3.20160212.0028.0.png


No handles with labels found to put in legend.


Writing snd-P3.20160212.0028.1.png


No handles with labels found to put in legend.


Writing snd-P3.20160212.0028.2.png


No handles with labels found to put in legend.


Writing snd-P3.20160212.0028.3.png


No handles with labels found to put in legend.


Writing snd-P3.20160212.0028.4.png


No handles with labels found to put in legend.


Writing snd-P3.20160212.0028.5.png


No handles with labels found to put in legend.


Writing snd-P3.20160212.0029.0.png


No handles with labels found to put in legend.


Writing snd-P3.20160212.0029.1.png


No handles with labels found to put in legend.


Writing snd-P3.20160212.0029.2.png


No handles with labels found to put in legend.


Writing snd-P3.20160212.0029.3.png


No handles with labels found to put in legend.


Writing snd-P3.20160212.0029.4.png


No handles with labels found to put in legend.


Writing snd-P3.20160212.0106.0.png


No handles with labels found to put in legend.


Writing snd-P3.20160212.0106.1.png


No handles with labels found to put in legend.


Writing snd-P3.20160212.0106.2.png


No handles with labels found to put in legend.


Writing snd-P3.20160212.0106.3.png


No handles with labels found to put in legend.


Writing snd-P3.20160212.0106.4.png


No handles with labels found to put in legend.


Writing snd-P3.20160212.0106.5.png


No handles with labels found to put in legend.


Writing snd-P3.20160212.0106.6.png


No handles with labels found to put in legend.


Writing snd-P3.20160212.0106.7.png


No handles with labels found to put in legend.


Writing snd-P3.20160212.0615.0.png


No handles with labels found to put in legend.


Writing snd-P3.20160212.0615.1.png


No handles with labels found to put in legend.


Writing snd-P3.20160212.0616.0.png


No handles with labels found to put in legend.


Writing snd-P3.20160212.0616.1.png


No handles with labels found to put in legend.


Writing snd-P3.20160212.2003.0.png


No handles with labels found to put in legend.


Writing snd-P3.20160212.2003.1.png


No handles with labels found to put in legend.


Writing snd-P3.20160212.2003.2.png


No handles with labels found to put in legend.


Writing snd-P3.20160212.2003.3.png


No handles with labels found to put in legend.


Writing snd-P3.20160216.2144.0.png


No handles with labels found to put in legend.


Writing snd-P3.20160216.2144.1.png


No handles with labels found to put in legend.


Writing snd-P3.20160216.2144.3.png


No handles with labels found to put in legend.


Writing snd-P3.20160216.2145.11.png


No handles with labels found to put in legend.


Writing snd-P3.20160216.2159.3.png


No handles with labels found to put in legend.


Writing snd-P3.20160216.2159.4.png


No handles with labels found to put in legend.


Writing snd-P3.20160216.2159.5.png


No handles with labels found to put in legend.


Writing snd-P3.20160216.2159.6.png


No handles with labels found to put in legend.


Writing snd-P3.20160216.2159.7.png


No handles with labels found to put in legend.


Writing snd-P3.20160225.1621.0.png


No handles with labels found to put in legend.


Writing snd-P3.20160225.1621.1.png


No handles with labels found to put in legend.


Writing snd-P3.20160225.1621.2.png


No handles with labels found to put in legend.


Writing snd-P3.20160225.1621.3.png


No handles with labels found to put in legend.


Writing snd-P3.20160225.1621.4.png


No handles with labels found to put in legend.


Writing snd-P3.20160225.1621.5.png


No handles with labels found to put in legend.


Writing snd-P3.20160225.1621.6.png


No handles with labels found to put in legend.


Writing snd-P3.20160225.1621.7.png


No handles with labels found to put in legend.


Writing snd-P3.20160225.1622.5.png


No handles with labels found to put in legend.


Writing snd-P3.20160225.1719.0.png


No handles with labels found to put in legend.


Writing snd-P3.20160225.1720.0.png


No handles with labels found to put in legend.


Writing snd-P3.20160225.1720.1.png


No handles with labels found to put in legend.


Writing snd-P3.20160225.1720.2.png


No handles with labels found to put in legend.


Writing snd-P3.20160225.1721.0.png


No handles with labels found to put in legend.


Writing snd-P3.20160225.1721.1.png


No handles with labels found to put in legend.


Writing snd-P3.20160225.1721.2.png


No handles with labels found to put in legend.


Writing snd-P3.20160225.1722.2.png


No handles with labels found to put in legend.


Writing snd-P3.20160225.1724.1.png


No handles with labels found to put in legend.


Writing snd-P3.20160225.1724.2.png


No handles with labels found to put in legend.


Writing snd-P3.20160225.1725.0.png


No handles with labels found to put in legend.


Writing snd-P3.20160225.1725.1.png


No handles with labels found to put in legend.


Writing snd-P3.20160225.1725.2.png


No handles with labels found to put in legend.


Writing snd-P3.20160225.1725.3.png


No handles with labels found to put in legend.


Writing snd-P3.20160226.0634.0.png


No handles with labels found to put in legend.


Writing snd-P3.20160226.1056.0.png


No handles with labels found to put in legend.


Writing snd-P3.20160226.1129.0.png


No handles with labels found to put in legend.


Writing snd-P3.20160226.1130.0.png


No handles with labels found to put in legend.


Writing snd-P3.20160226.1130.1.png


No handles with labels found to put in legend.


Writing snd-P3.20160226.1132.0.png


No handles with labels found to put in legend.


Writing snd-P3.20160226.1133.0.png


No handles with labels found to put in legend.


Writing snd-P3.20160226.1133.1.png


No handles with labels found to put in legend.


Writing snd-P3.20160226.1233.1.png


No handles with labels found to put in legend.


Writing snd-P3.20160226.1253.0.png


No handles with labels found to put in legend.


Writing snd-P3.20160227.1135.2.png


No handles with labels found to put in legend.


Writing snd-P3.20160227.1141.1.png


No handles with labels found to put in legend.


Writing snd-P3.20160227.1143.1.png


No handles with labels found to put in legend.


Writing snd-P3.20160227.1143.3.png


No handles with labels found to put in legend.


Writing snd-P3.20160227.1144.1.png


No handles with labels found to put in legend.


Writing snd-P3.20160227.1149.3.png


No handles with labels found to put in legend.


Writing snd-P3.20160227.1215.1.png


No handles with labels found to put in legend.


Writing snd-P3.20160227.1215.3.png


No handles with labels found to put in legend.


Writing snd-P3.20160227.1220.0.png


No handles with labels found to put in legend.


Writing snd-P3.20160227.1220.1.png


No handles with labels found to put in legend.


Writing snd-P3.20160227.1222.1.png


No handles with labels found to put in legend.


Writing snd-P3.20160227.1227.0.png


No handles with labels found to put in legend.


Writing snd-P3.20160227.1227.1.png


No handles with labels found to put in legend.


Writing snd-P3.20160227.1227.3.png


No handles with labels found to put in legend.


Writing snd-P3.20160227.1228.5.png


No handles with labels found to put in legend.


Writing snd-P3.20160227.1229.1.png


No handles with labels found to put in legend.


Writing snd-P3.20160227.1233.5.png


No handles with labels found to put in legend.


Writing snd-P3.20160227.1234.0.png


No handles with labels found to put in legend.


Writing snd-P3.20160227.1234.6.png


No handles with labels found to put in legend.


Writing snd-P3.20160227.1234.7.png


No handles with labels found to put in legend.


Writing snd-P3.20160227.1257.0.png


No handles with labels found to put in legend.


Writing snd-P3.20160227.1257.1.png


No handles with labels found to put in legend.


Writing snd-P3.20160227.2114.0.png


No handles with labels found to put in legend.


Writing snd-P3.20160301.0100.3.png


No handles with labels found to put in legend.


Writing snd-P3.20160301.0545.0.png


No handles with labels found to put in legend.


Writing snd-P3.20160301.0547.0.png


No handles with labels found to put in legend.


Writing snd-P3.20160301.0615.0.png


No handles with labels found to put in legend.


Writing snd-P3.20160301.0615.1.png


No handles with labels found to put in legend.


Writing snd-P3.20160301.0615.2.png


No handles with labels found to put in legend.


Writing snd-P3.20160301.0615.3.png


No handles with labels found to put in legend.


Writing snd-P3.20160301.0707.0.png


No handles with labels found to put in legend.


Writing snd-P3.20160301.0707.1.png


No handles with labels found to put in legend.


Writing snd-P3.20160301.0707.2.png


No handles with labels found to put in legend.


Writing snd-P3.20160301.0707.3.png


No handles with labels found to put in legend.


Writing snd-P3.20160301.0708.0.png


No handles with labels found to put in legend.


Writing snd-P3.20160301.0708.1.png


No handles with labels found to put in legend.


Writing snd-P3.20160301.0709.0.png


No handles with labels found to put in legend.


Writing snd-P3.20160301.0709.1.png


No handles with labels found to put in legend.


Writing snd-P3.20160301.2011.0.png


No handles with labels found to put in legend.


Writing snd-P3.20160301.2011.1.png


No handles with labels found to put in legend.


Writing snd-P3.20160301.2113.0.png


No handles with labels found to put in legend.


Writing snd-P3.20160301.2153.4.png


No handles with labels found to put in legend.


Writing snd-P3.20160301.2154.2.png


No handles with labels found to put in legend.


Writing snd-P3.20160301.2159.0.png


No handles with labels found to put in legend.


Writing snd-P3.20160301.2159.1.png


No handles with labels found to put in legend.


Writing snd-P3.20160301.2201.0.png


No handles with labels found to put in legend.


Writing snd-P3.20160301.2201.1.png


No handles with labels found to put in legend.


Writing snd-P3.20160301.2202.0.png


No handles with labels found to put in legend.


Writing snd-P3.20160301.2219.7.png


No handles with labels found to put in legend.


Writing snd-P3.20160301.2220.6.png


No handles with labels found to put in legend.


Writing snd-P3.20160301.2222.1.png


No handles with labels found to put in legend.


Writing snd-P3.20160301.2222.5.png


No handles with labels found to put in legend.


Writing snd-P3.20160301.2226.3.png


No handles with labels found to put in legend.


Writing snd-P3.20160302.0259.0.png


No handles with labels found to put in legend.


Writing snd-P3.20160302.0431.0.png


No handles with labels found to put in legend.


Writing snd-P3.20160302.0438.0.png


No handles with labels found to put in legend.


Writing snd-P3.20160302.0442.5.png


No handles with labels found to put in legend.


Writing snd-P3.20160302.0442.9.png


No handles with labels found to put in legend.


Writing snd-P3.20160302.0455.20.png


No handles with labels found to put in legend.


Writing snd-P3.20160302.0456.14.png


No handles with labels found to put in legend.


Writing snd-P3.20160302.0456.33.png


No handles with labels found to put in legend.


Writing snd-P3.20160302.0456.8.png


No handles with labels found to put in legend.


Writing snd-P3.20160302.0457.8.png


No handles with labels found to put in legend.


Writing snd-P3.20160302.0458.1.png


No handles with labels found to put in legend.


Writing snd-P3.20160302.0502.0.png


No handles with labels found to put in legend.


Writing snd-P3.20170312.0328.1.png


No handles with labels found to put in legend.


Writing snd-P3.20170312.0459.10.png


No handles with labels found to put in legend.


Writing snd-P3.20170312.0641.0.png


No handles with labels found to put in legend.


Writing snd-P3.20170312.0656.1.png


No handles with labels found to put in legend.


Writing snd-P3.20170312.0741.0.png


No handles with labels found to put in legend.


Writing snd-P3.20170312.0804.0.png


No handles with labels found to put in legend.


Writing snd-P3.20170312.0804.1.png


No handles with labels found to put in legend.


Writing snd-P3.20170312.0929.0.png


No handles with labels found to put in legend.


Writing snd-P3.20170323.1900.0.png


No handles with labels found to put in legend.


Writing snd-P3.20170323.2133.0.png


No handles with labels found to put in legend.


Writing snd-P3.20170323.2134.0.png


No handles with labels found to put in legend.


Writing snd-P3.20170324.0007.0.png


No handles with labels found to put in legend.


Writing snd-P3.20170324.0007.2.png


No handles with labels found to put in legend.


Writing snd-P3.20170324.0009.0.png


No handles with labels found to put in legend.


Writing snd-P3.20170324.0036.0.png


No handles with labels found to put in legend.


Writing snd-P3.20170324.0036.1.png


No handles with labels found to put in legend.


Writing snd-P3.20170324.0328.1.png


No handles with labels found to put in legend.


Writing snd-P3.20170324.0605.11.png


No handles with labels found to put in legend.


Writing snd-P3.20170324.0606.11.png


No handles with labels found to put in legend.


Writing snd-P3.20170324.0608.3.png


No handles with labels found to put in legend.


Writing snd-P3.20170324.0632.1.png


No handles with labels found to put in legend.


Writing snd-P3.20170324.0929.5.png


No handles with labels found to put in legend.


Writing snd-P3.20181220.2110.1.png


No handles with labels found to put in legend.


Writing snd-P3.20181220.2110.2.png


No handles with labels found to put in legend.


Writing snd-P3.20181220.2110.3.png


No handles with labels found to put in legend.


Writing snd-P3.20181220.2110.4.png


No handles with labels found to put in legend.


Writing snd-P3.20181220.2110.5.png


No handles with labels found to put in legend.


Writing snd-P3.20181220.2110.6.png


No handles with labels found to put in legend.


Writing snd-P3.20181221.0332.1.png


No handles with labels found to put in legend.


Writing snd-P3.20181221.0333.0.png


No handles with labels found to put in legend.


Writing snd-P3.20181221.0333.1.png


No handles with labels found to put in legend.


Writing snd-P3.20181221.0333.2.png


No handles with labels found to put in legend.


Writing snd-P3.20181221.0333.3.png


No handles with labels found to put in legend.


Writing snd-P3.20181221.0333.4.png


No handles with labels found to put in legend.


Writing snd-P3.20181221.0333.5.png


No handles with labels found to put in legend.


Writing snd-P3.20181221.0531.4.png


No handles with labels found to put in legend.


Writing snd-P3.20181221.0531.5.png


<Figure size 576x432 with 0 Axes>

In [25]:
for filename in os.listdir('C:/Users/Vaclav/Documents/Diploma/Clean Signals/ETHALON_SIGNAL'):
    filename = os.path.splitext(filename)[0]
    filename = filename+'.png'
    #-----Reading the image-----------------------------------------------------
    img = cv2.imread(filename, 1)
    lab = cv2.cvtColor(img, cv2.COLOR_BGR2LAB)
    l, a, b = cv2.split(lab)
    clahe = cv2.createCLAHE(clipLimit=3.0, tileGridSize=(8,8))
    cl = clahe.apply(l)
    limg = cv2.merge((cl,a,b))
    final = cv2.cvtColor(limg, cv2.COLOR_LAB2BGR)
    crop_img = img
    gray = cv2.cvtColor(crop_img,cv2.COLOR_BGR2GRAY)
    edges = cv2.Canny(gray, 75, 150)
    #lines = cv2.HoughLinesP(edges, 1, np.pi/180, 30, maxLineGap=250)
    lines = cv2.HoughLinesP(edges,rho = 1,theta = np.pi/180, threshold = 30, minLineLength = 0, maxLineGap = 250)
    for line in lines:
        x1, y1, x2, y2 = line[0]
        cv2.line(crop_img, (x1, y1), (x2, y2), (0, 0, 128), 1)
    cv2.imwrite(os.path.join(linePath, 'lines_'+filename),crop_img)
    cv2.imwrite(os.path.join(edgePath, 'edges_'+filename),edges)   
print(lines)

[[[ 300 1203 2005 1203]]

 [[ 300 1198 1996 1198]]

 [[ 534 1206 1792 1206]]

 [[ 300 1199 1997 1199]]

 [[ 300 1200 2003 1200]]

 [[ 300 1201 2005 1201]]

 [[ 299 1202 1886 1202]]

 [[ 300 1204 1873 1204]]]


In [26]:
len(lines)

8